services: 
  app:
    image: cloud_app
    volumes:
      - .:/usr/src
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - db

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: