services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: rails server -b 0.0.0.0
    depends_on:
      - db
      - calculation_service
    environment:
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  calculation_service:
    image: calculation_service
    ports:
      - 3005:3005
    command: ruby http_service.rb

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379/0

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  postgres:
  bundle:
  rabbit:
  redis:
