services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: rails server -b 0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  bundle:
  